data:extend{
    {
        name = 'maraxsis-wyrm-quality',
        setting_type = 'startup',
        type = 'bool-setting',
        order = 'a',
        default_value = true,
    },
    {
        name = 'maraxsis-wyrm-quality-multiplier',
        setting_type = 'startup',
        type = 'double-setting',
        order = 'a',
		minimum_value = 0.0,
		maximum_value = 50,
        default_value = 1.0,
    },
    {
        name = 'maraxsis-wyrm-spawner-density',
        setting_type = 'startup',
        type = 'double-setting',
        order = 'a',
		minimum_value = 0.1,
		maximum_value = 10,
        default_value = 1.0,
    },
    {
        name = 'maraxsis-wyrm-spawn-rate',
        setting_type = 'startup',
        type = 'double-setting',
        order = 'a',
		minimum_value = 0.1,
		maximum_value = 60,
        default_value = 1.0,
    },
    {
        name = 'maraxsis-wyrm-drops-multiplier',
        setting_type = 'startup',
        type = 'double-setting',
        order = 'a',
		minimum_value = 1.0,
		maximum_value = 50,
        default_value = 1.0,
    },
}